### ISSUE TITLE
fatal error: unistd.h: No such file or directory

### ISSUE THREAD

**Issue by suesunna** [avBuffer/caffe_ssd-android-lib#1]
/caffe_ssd-android-lib/boost/boost_1_56_0/boost/config/stdlib/libstdcpp3.hpp:77:22: fatal error: unistd.h: No such file or directory
 #  include <unistd.h>
                      ^
compilation terminated.

=====================
I use macos , does it use android-ndk's unistd.h

**Comment by avBuffer** [comment]
remark it
